default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: root
  pool: 5
  timeout: 5000
  host: localhost
development:
  <<: *default
  database: roshan
test:
  <<: *default
  database: roshan_test
production:
  <<: *default
  database: roshan